### ISSUE TITLE
Update plugin versions to those with recent Java-9 fixes

### ISSUE THREAD

**Issue by ansell** [gbif/motherpom#2]
There have been some plugin updates recently to fix some initial Java-9 issues. Updating to these will enable basic testing under Java-9 as the release candidates the GA releases are pushed out in the next two months.

**Comment by timrobertson100** [comment]
Thanks for your work here @ansell.
The MP versions have been neglected for too long. Do you have more changes you wish applied, or would you be happy for a release?

**Comment by ansell** [comment]
These changes made it possible for me to compile and test gbif-common and dwca-io using 9-ea (without using toolchains.xml to force the use of the target JDK version as is recommended for both Java-8 and Java-9 since they changed the backwards compatibility matrices http://openjdk.java.net/jeps/182 ), but I haven't tested other libraries or JDK versions to check there weren't regressions on them.

A long term goal may be to add support for toolchains.xml to ensure that devs/CI are releasing artifacts using the JDK they are targeting to, but adding animal-sniffer-maven-plugin and maven-enforcer-plugin should be enough in the short term to ensure that libraries don't get released that use future JDK APIs or class file versions. 

https://maven.apache.org/guides/mini/guide-using-toolchains.html 

http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/usage.html

http://www.mojohaus.org/extra-enforcer-rules/enforceBytecodeVersion.html

I will add animal-sniffer-maven-plugin and maven-enforcer-plugin here, but you would need to plan for toolchains.xml as every dev would need to add it to their machine and you need conventions for the JDK names (so gets messy without agreeing on the convention first).

A good compact ref for the three is:

https://stackoverflow.com/a/38307099

**Comment by ansell** [comment]
To support animal-sniffer, there are two new properties that define the signature to use. These need to be configured in child projects whenever they change the jdkLevel, as gbif-common and dwca-io do.

E.g., to use the Java-8 signatures from https://search.maven.org/#artifactdetails%7Corg.codehaus.mojo.signature%7Cjava18%7C1.0%7Cpom you need to now specify three properties instead of just the jdkLevel

This could be simplified by changing motherpom to use jdk1.8 if the dependencies have effectively already upgraded.

```
  <properties>
    <jdkLevel>1.8</jdkLevel>
    <animal-sniffer-signature.artifact>java18</animal-sniffer-signature.artifact>
    <animal-sniffer-signature.version>1.0</animal-sniffer-signature.version>
  </properties>
```

The maven-enforcer-plugin was also in build->plugins here in motherpom, so I added animal-sniffer as well. This means there are no changes necessary to child modules unless they need to change the jdk level.

It is ready for testing on other modules (only 

My test maven/java version was:

```
$ mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T05:39:06+10:00)
Maven home: /opt/apache-maven-3.5.0
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-78-generic", arch: "amd64", family: "unix"
```

**Comment by ansell** [comment]
I haven't found a module so far in testing that hasn't already switched to java8, so I switched the default here to that. If there are modules that require java7 still, the three properties can be set back again, rather than setting all three for every java8 module.
